export interface RuleDoc {
  why: string;
  how: string[];
  /** 1–10: how much fixing this tends to matter. */
  impact: number;
}

const r = (impact: number, why: string, ...how: string[]): RuleDoc => ({ impact, why, how });

/**
 * Plain-language guidance per rule id. The analyzers decide *whether* something
 * is wrong; this table decides *what to tell the developer* — no LLM involved.
 */
export const RULES: Record<string, RuleDoc> = {
  // ── Performance ──
  'perf.lcp': r(10, 'LCP measures when the main content becomes visible; it is the strongest proxy for perceived load speed.',
    'Preload the LCP resource: <link rel="preload" as="image" href="…" fetchpriority="high">.',
    'Remove render-blocking CSS/JS ahead of the LCP element and compress the hero asset.',
    'Reduce server latency (TTFB) with caching or a CDN.'),
  'perf.cls': r(9, 'Unexpected movement makes users misclick and lose their place.',
    'Give images, video and iframes explicit width/height or aspect-ratio.',
    'Reserve space for ads, embeds and late-injected banners (min-height).',
    'Avoid inserting content above existing content; animate with transform instead of layout properties.'),
  'perf.inp': r(9, 'INP is how long the page takes to visually respond to input; slow handlers feel broken.',
    'Break long event handlers into chunks (scheduler.yield / setTimeout) and defer non-urgent work.',
    'Move heavy computation to a Web Worker and debounce high-frequency handlers.',
    'Reduce DOM size and avoid forced synchronous layout in handlers.'),
  'perf.fcp': r(7, 'FCP is the first moment the user sees anything; long blank screens feel like failures.',
    'Inline critical CSS and defer the rest; avoid blocking scripts in <head>.',
    'Use font-display: swap so text is not hidden while fonts load.'),
  'perf.ttfb': r(8, 'Every other metric starts after the first byte, so slow servers tax them all.',
    'Cache HTML at the edge/CDN and enable HTTP keep-alive and HTTP/2+.',
    'Profile the backend: slow queries, cold starts and redirects are the usual causes.'),
  'perf.tbt': r(8, 'Long main-thread tasks block input and rendering; TBT predicts poor INP.',
    'Split bundles and lazy-load code that is not needed for first interaction.',
    'Audit third-party scripts — they are a common source of long tasks.'),
  'perf.lcp-lazy': r(9, 'loading="lazy" postpones the request until layout, directly delaying the largest visible image.',
    'Remove loading="lazy" from above-the-fold images and add fetchpriority="high" to the LCP image.'),
  'perf.lcp-priority': r(5, 'Without a priority hint the browser may fetch the hero image after scripts and styles.',
    'Add fetchpriority="high" to the LCP <img> (and preload it if it is a CSS background).'),
  'perf.dom-size': r(6, 'Large DOMs increase style recalculation, layout cost and memory.',
    'Virtualise long lists and paginate or lazy-render offscreen sections.',
    'Remove wrapper elements added by components that do no layout work.'),
  'perf.dom-depth': r(4, 'Deep nesting makes selector matching and layout more expensive.', 'Flatten wrappers; prefer CSS grid/gap over nested spacer elements.'),

  // ── Responsive ──
  'resp.no-viewport-meta': r(10, 'Without it, mobile browsers emulate a ~980px desktop viewport and shrink the page.',
    'Add <meta name="viewport" content="width=device-width, initial-scale=1"> to <head>.'),
  'resp.viewport-fixed-width': r(7, 'A fixed viewport width stops the layout adapting to the device.',
    'Use width=device-width, initial-scale=1.'),
  'resp.horizontal-scroll': r(9, 'Sideways scrolling on mobile is one of the most visible responsive bugs.',
    'Find the widest elements (highlighted) and give them max-width: 100%.',
    'Make images/video/iframes fluid: img, video { max-width: 100%; height: auto }.',
    'Let long strings wrap with overflow-wrap: anywhere; wrap wide tables in a scroll container.'),
  'resp.no-breakpoints': r(2, 'Pure fluid layouts can work, but most designs need at least one breakpoint.',
    'Confirm layouts adapt using the Responsive Lab; add @media (min-width) rules where content breaks.'),

  // ── Accessibility ──
  'a11y.contrast': r(10, 'Low contrast text is hard or impossible to read for many users, in bright light, or on cheap screens.',
    'Aim for 4.5:1 for body text and 3:1 for large text (WCAG 1.4.3).',
    'Darken text or lighten/darken the background; the temporary fix shows a compliant colour.',
    'Define text/background pairs as design tokens and test them once.'),
  'a11y.contrast-unknown': r(3, 'The tool cannot compute contrast over images or gradients.', 'Check these manually, or place text on a solid or scrimmed surface.'),
  'a11y.img-alt-missing': r(9, 'Screen readers fall back to the file name when alt is absent.',
    'Describe informative images with alt text.', 'Use alt="" for purely decorative images so they are skipped.'),
  'a11y.img-alt-poor': r(5, 'Alt text like "image" or "IMG_1234.jpg" conveys nothing.', 'Write what the image communicates in context, not what it is.'),
  'a11y.label-missing': r(10, 'Unlabelled fields are announced as "edit text" with no purpose; placeholders vanish while typing.',
    'Use <label for="id"> (preferred), or aria-label / aria-labelledby.', 'Keep placeholders as hints only.'),
  'a11y.button-name': r(9, 'Icon buttons without a name are announced as just "button".',
    'Add aria-label="Close" or visually hidden text inside the button.'),
  'a11y.link-name': r(9, 'Empty links are announced as "link" with no destination.',
    'Add link text, or aria-label for icon links. Give linked images a meaningful alt.'),
  'a11y.lang-missing': r(7, 'Screen readers use lang to choose pronunciation rules.', 'Set <html lang="en"> (or the correct BCP-47 tag).'),
  'a11y.title-missing': r(7, 'The title is announced on load and used for tabs, history and bookmarks.', 'Add a unique, descriptive <title>.'),
  'a11y.zoom-disabled': r(8, 'Users with low vision rely on pinch-zoom (WCAG 1.4.4).',
    'Remove user-scalable=no and any maximum-scale below 5 from the viewport meta tag.'),
  'a11y.no-main': r(5, 'Landmarks let keyboard and screen-reader users skip repeated content.', 'Wrap the primary content in <main>.'),
  'a11y.no-h1': r(5, 'The h1 names the page for assistive tech and search engines.', 'Add one <h1> describing the page.'),
  'a11y.multiple-h1': r(2, 'Several h1s can blur the page outline.', 'Prefer one h1 and use h2–h6 for sections.'),
  'a11y.heading-order': r(5, 'Skipped levels make the document outline confusing.', 'Nest headings sequentially; style with CSS rather than picking a level for its size.'),
  'a11y.heading-empty': r(4, 'Empty headings are announced with no content.', 'Remove the element or add text.'),
  'a11y.target-size-minimum': r(7, 'Tiny targets are hard to hit for anyone with motor impairment or on touch screens (WCAG 2.5.8).',
    'Make interactive elements at least 24×24 CSS px; 44×44 is the comfortable touch size.', 'Add padding rather than enlarging the icon.'),
  'a11y.target-size-comfortable': r(5, 'Apple HIG and Material recommend 44–48px touch targets.',
    'Increase padding or min-height/min-width to 44px on touch layouts.'),
  'a11y.focus-outline-removed': r(8, 'Keyboard users cannot see where they are when outlines are removed (WCAG 2.4.7).',
    'Never use outline:none without a replacement. Style :focus-visible with a clear ring.'),
  'a11y.clickable-not-focusable': r(7, 'Click handlers on <div>/<span> are unreachable by keyboard and invisible to screen readers.',
    'Use <button> or <a href>. If you must keep a div, add role, tabindex="0" and key handlers.'),
  'a11y.aria-hidden-focusable': r(7, 'Keyboard focus lands on content assistive tech cannot see.', 'Remove aria-hidden, or make the content non-focusable (tabindex="-1" / inert).'),
  'a11y.invalid-role': r(5, 'Unknown roles are ignored, so the intended semantics are lost.', 'Use a valid WAI-ARIA role, or a native element that has the semantics built in.'),
  'a11y.aria-broken-reference': r(5, 'References to missing ids silently produce no accessible name or description.', 'Fix the id or remove the attribute.'),
  'a11y.duplicate-id': r(5, 'Duplicate ids break <label for> and ARIA references.', 'Make ids unique.'),
  'a11y.positive-tabindex': r(5, 'Positive tabindex values override the natural tab order and are hard to maintain.', 'Use tabindex="0" or "-1" and fix the DOM order instead.'),

  // ── Images ──
  'img.broken': r(8, 'Broken images look unprofessional and hurt trust.', 'Check the URL, permissions and CORS; provide a fallback with onerror or <picture>.'),
  'img.oversized': r(8, 'Bytes you ship but pixels the user never sees.',
    'Export at 2× the displayed size at most.',
    'Serve responsive variants with srcset and sizes, or an image CDN (?w=…).'),
  'img.large-file': r(8, 'Heavy images dominate page weight and delay LCP.',
    'Compress (Squoosh, sharp, imagemin) and use AVIF/WebP.', 'Aim for under 100–200 KB for typical content images.'),
  'img.legacy-format': r(6, 'Modern codecs are typically 25–50% smaller at the same quality.',
    'Serve AVIF/WebP with a JPEG fallback: <picture><source type="image/avif" srcset="…"><img …></picture>.'),
  'img.no-dimensions': r(8, 'Without intrinsic size the browser cannot reserve space, so content jumps when the image loads.',
    'Add width and height attributes matching the intrinsic size; keep img { height: auto } in CSS.',
    'Or set aspect-ratio in CSS.'),
  'img.lazy-above-fold': r(7, 'Lazy-loading visible images delays them behind layout.', 'Remove loading="lazy" for images in the first viewport.'),
  'img.no-lazy': r(5, 'Offscreen images compete with critical resources for bandwidth.', 'Add loading="lazy" (and decoding="async") to below-the-fold images.'),
  'img.no-srcset': r(4, 'Phones download the same pixels as desktops.', 'Provide srcset with width descriptors and an accurate sizes attribute.'),
  'img.srcset-no-sizes': r(6, 'With no sizes, the browser assumes 100vw and over-fetches.', 'Add sizes="(min-width: 800px) 50vw, 100vw" matching the layout.'),
  'img.undersized': r(3, 'Upscaled bitmaps look blurry.', 'Provide a higher-resolution source or shrink the rendered size.'),

  // ── Bundles ──
  'bundle.large-js': r(8, 'Every KB of JS must be downloaded, parsed and executed.',
    'Code-split by route and lazy-load below-the-fold features.', 'Analyse the bundle (source-map-explorer, webpack-bundle-analyzer) and drop heavy dependencies.'),
  'bundle.large-css': r(6, 'CSS blocks rendering until parsed.', 'Remove unused rules (coverage tab), split per route, minify and compress.'),
  'bundle.total-js': r(8, 'Total JS weight drives parse/execute time on mid-range phones.', 'Set a JS budget (e.g. 170 KB gzip) and enforce it in CI.'),
  'bundle.total-css': r(5, 'Large CSS slows first paint.', 'Purge unused CSS and split critical from non-critical.'),
  'bundle.render-blocking-js': r(8, 'Blocking scripts halt HTML parsing until they run.', 'Add defer (or async for independent scripts), or move them to the end of <body>.'),
  'bundle.render-blocking-css': r(6, 'Stylesheets in <head> block first paint.', 'Inline critical CSS and load the rest with media="print" onload swap, or split by media query.'),
  'bundle.uncompressed': r(8, 'Text compresses 70–90%; sending it raw wastes bandwidth.', 'Enable Brotli (preferred) or gzip at the server/CDN for JS, CSS, HTML and SVG.'),
  'bundle.third-party': r(7, 'Third-party code adds requests and main-thread work you do not control.',
    'Remove tags that are not earning their cost; load the rest with async/defer or after interaction.', 'Self-host critical third-party assets.'),
  'bundle.many-scripts': r(5, 'Many small requests increase overhead and delay hydration.', 'Bundle related modules; use HTTP/2+ and preload only what is critical.'),
  'bundle.inline-large': r(5, 'Large inline blocks cannot be cached independently.', 'Move large inline scripts/styles into external, cacheable files.'),
  'bundle.duplicate-script': r(6, 'Loading a script twice doubles its cost and may cause double initialisation.', 'Deduplicate the include.'),

  // ── UI / UX ──
  'ux.color-sprawl': r(4, 'Many one-off colours make a UI feel inconsistent and are hard to theme.', 'Define a palette of tokens (brand, neutral, semantic) and replace raw values.'),
  'ux.near-duplicate-colors': r(3, 'Visually identical colours defined separately drift over time.', 'Merge near-duplicates into a single token.'),
  'ux.many-hues': r(3, 'Too many hue families dilute the brand.', 'Choose one primary accent; derive other colours from tints/shades.'),
  'ux.too-many-fonts': r(6, 'Extra families cost bytes and weaken typographic hierarchy.', 'Limit to 1–2 families; use weight and size for hierarchy.'),
  'ux.too-many-sizes': r(5, 'A long tail of sizes signals no type scale.', 'Adopt a modular scale (e.g. 1.25) and expose sizes as tokens.'),
  'ux.small-text': r(6, 'Text under 12px is hard to read, particularly on mobile.', 'Raise to at least 12px, preferably 14–16px for body.'),
  'ux.line-height-tight': r(5, 'Tight leading hurts readability and fails WCAG 1.4.12 spacing overrides.', 'Use line-height 1.4–1.6 for body text.'),
  'ux.line-length': r(5, 'Very long lines are tiring to track across.', 'Constrain text with max-width: 65–75ch.'),
  'ux.no-doctype': r(8, 'Quirks mode changes the box model and many layout behaviours.', 'Add <!DOCTYPE html> as the first line.'),
  'ux.off-grid-spacing': r(3, 'Spacing off a consistent grid makes alignment feel arbitrary.', 'Use a 4px (or 8px) spacing scale via tokens.'),
  'ux.too-many-spacing-values': r(3, 'Dozens of spacing values are hard to keep consistent.', 'Define 6–10 spacing tokens.'),
  'ux.radius-inconsistency': r(4, 'Mixed corner radii read as visual noise.', 'Define 2–3 radius tokens (small, medium, pill).'),
  'ux.button-inconsistency': r(6, 'Different button looks confuse users about what is primary.', 'Consolidate to a single Button component with variants.'),
  'ux.generic-link-text': r(5, '"Click here" is meaningless out of context.', 'Use descriptive text: "Read the pricing guide".'),
  'ux.dead-links': r(3, 'href="#" jumps to the top and signals unfinished work.', 'Use <button> for actions; link to real destinations.'),
  'ux.form-no-submit': r(3, 'Hidden submit behaviour is not discoverable.', 'Add a visible submit button.'),
  'ux.autocomplete-missing': r(3, 'Autofill reduces typing errors and effort (WCAG 1.3.5).', 'Add autocomplete="email" | "tel" | "current-password" | "new-password".'),
  'ux.no-meta-description': r(3, 'Search and sharing previews fall back to arbitrary text.', 'Add <meta name="description" content="…"> (≈150 chars).'),
  'ux.no-favicon': r(2, 'Generic tab icons look unfinished; /favicon.ico is requested anyway.', 'Add <link rel="icon" href="/favicon.svg">.'),
  'ux.no-design-tokens': r(3, 'Without tokens, consistency depends on discipline.', 'Declare colours, spacing and type as CSS custom properties on :root.'),
};
